# Exports
export DOTS=~/dotfiles/
export ALXD=~/alxandria/
export PYTH=~/dotfiles/scripts/lang/python

# Aliases
alias alx="cd ~/alxandria/"
alias aur="yay -Qq | grep"
alias btop="bashtop"
alias cl="clear"
alias clip="xclip -sel c <"
alias codeconf="nvim ~/dotfiles/code/.config/Code/User/settings.json"
alias cp="cp -i"
alias dfi="df --si -T"
alias dots="cd ~/dotfiles/"
alias egrep="egrep --color=auto"
alias ff="fastfetch --data-raw '$(pokemon-colorscripts -n mudkip --no-title)'"
alias fishconf="nvim ~/dotfiles/fish/.config/fish/config.fish"
alias grep="grep --color=auto"
alias hyprconf="cd ~/.config/hypr/"
alias i3conf="sudo nvim ~/dotfiles/i3/.config/i3/config"
alias kittyconf="nvim ~/dotfiles/kitty/.config/kitty/kitty.conf"
alias ls="ls -lahc --color=auto"
alias matrix="cmatrix -C blue"
alias mkdir="mkdir -p"
alias mv="mv -i"
alias nanos="sudo nano"
alias nvimconf="nvim ~/dotfiles/neovim/.config/nvim/init.lua"
alias please="sudo $(history -p !!)"
alias pokemon="pokemon-colorscripts -n"
alias pyth="cd ~/dotfiles/scripts/lang/python"
alias sp="sudo pacman"
alias super="sudo"
alias unstow="stow --delete"
alias waybar="waybar & disown"
alias wayboff="pkill waybar"
alias waybconf="nvim ~/.config/waybar/config.jsonc"
alias waybreset="pkill waybar && waybar & disown"
alias waybst="nvim ~/.config/waybar/style.css"
alias yaziconf="nvim ~/dotfiles/yazi/.config/yazi/yazi.toml"
alias z="cd"
