[flavor]
use = "catppuccin-macchiato"
dark = "catppuccin-macchiato"

[icon]
prepend_dirs = [
	{ name = "Documents", text = "\uf07c", fg = "#00bcd4" },
]

[indicator]
current = { bg = "#494d64", bold = true }
parent = { bg = "#494d64", bold = true }
